### PR TITLE
Solved bug - Send postcards via email

### LINKED ISSUE #37: [Bug] Display postcard on email
We found out that **base64 encoding** does not work on Gmail.
We need to change the approach.

### LINKED ISSUE #38: [Bug] Code on master branch is not working
We need a healthy master branch.

### PR DESCRIPTION
**Pull request by Krechals**
Now the app is able to send postcards on Gmail.
Due to the fact that Gmail **blocks** certain CSS styles (position, top, right, left, etc.) and base64 encoding, the postcard is styled using **HTML tables**.
Sometimes **application/x-www-form-urlencoded** does NOT send the entire string, so I had to hard-code the entire html elements in Java. Probably this will work by sending the postcard from fronted to backend using **JSON**/**XML**/**Protobufs**.

### CODE REVIEW

File: src/main/java/com/google/sps/servlets/MailServlet.java [hunk 1]
```diff
@@ -79,10 +82,11 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
 * This function creates an email and sends it to the user
 **/
 
-  private String sendMultipartMail(String from, String to, String link) {
+  private String sendMultipartMail(String from, String to, String title, String message, String image) {
     Properties props = new Properties();
     Session session = Session.getDefaultInstance(props, null);
-
+    final String POSTCARD_CONTAINER = "<div class='pcard-container' id='pcard-design' style='background-attachment: scroll; background-image: url(\"https://i.ibb.co/JjqsjjL/postcard.jpg\"); background-repeat: no-repeat; background-size: 700px 500px; color: black; display: block; height: 500px; margin-left: auto; margin-right: auto; position: relative; text-align: center; width: 700px;'>";
```
Comment (maraPislar) [inline src/main/java/com/google/sps/servlets/MailServlet.java]: There is a lot of text on only one line. My suggestion is to distribute the string on the next lines.

File: src/main/java/com/google/sps/servlets/MailServlet.java [hunk 2]
```diff
@@ -91,11 +95,23 @@ private String sendMultipartMail(String from, String to, String link) {
...
       msg.setText(MSG_BODY);
 
-      String htmlBody = "<img src = " + "\"" + link + "\"" + "style=\"width:400px\">";
+      /*
+       * Problem: Sometimes application/x-www-form-urlencoded does NOT send the entire string.git 
+       * First solution: Use Java hard-coded html elements, instead of sending them from the front-end.
+       * TODO: Try to send JSON insted of application/x-www-form-urlencoded.
+       **/
+      final String htmlBody = POSTCARD_CONTAINER + 
+                  "<table cellpadding='0' cellspacing='0' width='640' align='center'><tbody><tr><td><table cellpadding='0' cellspacing='0' width='640' height='150' align='left'></table><table cellpadding='0' cellspacing='0' width='320' height='280' align='left'><td>" +
```
Comment (maraPislar) [inline src/main/java/com/google/sps/servlets/MailServlet.java]: Same here

**Review by maraPislar — CHANGES_REQUESTED** [review]

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 1 above)
Comment (nyotaL) [inline src/main/java/com/google/sps/servlets/MailServlet.java]: maybe better to pass string as a parameter? we can build it in js (or extract html of an element)

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 2 above)
Comment (Krechals) [reply src/main/java/com/google/sps/servlets/MailServlet.java]: Done

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 1 above)
Comment (Krechals) [reply src/main/java/com/google/sps/servlets/MailServlet.java]: Done

**Review by maraPislar — APPROVED** [review]

File: src/main/java/com/google/sps/servlets/MailServlet.java [hunk 3]
```diff
@@ -79,10 +82,16 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
 * This function creates an email and sends it to the user
 **/
 
-  private String sendMultipartMail(String from, String to, String link) {
+  private String sendMultipartMail(String from, String to, String title, String message, String image) {
     Properties props = new Properties();
     Session session = Session.getDefaultInstance(props, null);
-
+    final String POSTCARD_CONTAINER = "<div class='pcard-container' id='pcard-design' " +
```
Comment (jeadorf) [inline src/main/java/com/google/sps/servlets/MailServlet.java]: Constants are static final, see naming guidelines at
https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names
You can move that out into a static final field

File: src/main/java/com/google/sps/servlets/MailServlet.java [hunk 4]
```diff
@@ -79,10 +82,16 @@ public void doPost(HttpServletRequest request, HttpServletResponse response) thr
...
+                "style='background-attachment: scroll; " +
+                "background-image: url(\"https://i.ibb.co/JjqsjjL/postcard.jpg\"); " +
+                "background-repeat: no-repeat; background-size: 700px 500px; color: black; " +
+                "display: block; height: 500px; margin-left: auto; margin-right: auto ;" +
+                "position: relative; text-align: center; width: 700px;'>";
+    
     try {
       Message msg = new MimeMessage(session);
```
Comment (jeadorf) [inline src/main/java/com/google/sps/servlets/MailServlet.java]: `msg` might be more easily understood shorthand, but I think the saving of characters by omitting vowels is not worth it

File: src/main/webapp/script/postcardgen.js [hunk 5]
```diff
@@ -52,29 +52,126 @@ class Postcard {
...
+    message.style.fontFamily = "'Comic Sans MS', cursive, sans-serif";
+    message.style.fontSize = '30px';
+    message.style.maxWidth = '300px';
+    message.style.width = '250px';
+    message.appendChild(document.createTextNode(this._message));
+
+    return message;
+  }
+
+  addTitleEmailStyle() {
```
Comment (jeadorf) [inline src/main/webapp/script/postcardgen.js:76]: is it possible to put the style (which isn't dynamic) into the stylesheet, and just add a class attribute here?

**Review by jeadorf — APPROVED** [review]

**Review by nyotaL — CHANGES_REQUESTED** [review]

**Review by nyotaL — APPROVED** [review]

File: src/main/webapp/script/postcardgen.js (hunk 5 above)
Comment (Krechals) [reply src/main/webapp/script/postcardgen.js:76]: I did a search right now and this is possible. At the time of the implementation I didn't know is was possible.

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 1 above)
Comment (Krechals) [reply src/main/java/com/google/sps/servlets/MailServlet.java]: I had problems when I tried to do this because the string was truncated for some reason. I will try to search to see why this happened.

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 3 above)
Comment (Krechals) [reply src/main/java/com/google/sps/servlets/MailServlet.java]: Done

File: src/main/java/com/google/sps/servlets/MailServlet.java (hunk 4 above)
Comment (Krechals) [reply src/main/java/com/google/sps/servlets/MailServlet.java]: Done
